-- ═══════════════════════════════════════════════════════════════════════════
-- WrapSec Auth Event Expansion Migration
-- No schema changes — action and failure_reason are VARCHAR(50).
-- Extends enum values in application code only.
-- Run AFTER add_user_management.sql.
-- Idempotent — safe to run multiple times (comment-only, no DDL).
-- ═══════════════════════════════════════════════════════════════════════════

-- ── Extended action enum values ───────────────────────────────────────────────
--
-- All values are enum-controlled in domain/enums.py (AuthEventAction).
-- Existing values (unchanged):
--   login_success
--   login_failed
--
-- New values added in this release:
--   logout                — user logged out (manual, inactivity, or expired)
--   token_refresh_success — refresh token rotated, new access token issued
--   token_refresh_failed  — refresh attempt failed (see failure_reason)
--   session_expired       — JWT rejected by middleware (expired or invalid)

-- ── Extended failure_reason enum values ──────────────────────────────────────
--
-- All values are enum-controlled in domain/enums.py (AuthEventFailureReason).
-- Existing values (unchanged):
--   invalid_password
--   user_not_found
--   account_disabled
--   account_inactive
--   token_expired
--
-- New values added in this release:
--   token_invalid       — malformed or tampered JWT (not just expired)
--   inactivity          — client-side inactivity timer triggered logout
--   manual              — user clicked logout button
--   expired             — user acknowledged session expired
--   refresh_failed      — refresh token invalid, expired, or revoked
--   session_invalidated — token_version mismatch (password/role/dept change)

-- ── Logging ownership rules ───────────────────────────────────────────────────
--
-- Each event type is logged by exactly one owner. Never duplicated.
--
--   login_success         → services/auth/service.py :: login()
--   login_failed          → services/auth/service.py :: login()
--   logout                → services/auth/service.py :: logout()
--   token_refresh_success → services/auth/service.py :: refresh()
--   token_refresh_failed  → services/auth/service.py :: refresh()
--   session_expired       → api/v1/middleware/auth.py
--                           NOT logged for /v1/auth/refresh path
--                           NOT logged when no token is present
--
-- ── tenant_id / user_id NULL rules ───────────────────────────────────────────
--
--   login_success               → both set from user record
--   login_failed (wrong pw)     → both set from user record
--   login_failed (not found)    → both NULL
--   logout                      → both set from user record
--   token_refresh_success       → both set from user record
--   token_refresh_failed        → both NULL if token not found
--   session_expired (expired)   → extracted from payload if possible, else NULL
--   session_expired (invalid)   → both NULL
--
-- ── NullPool session pattern ──────────────────────────────────────────────────
--
-- All auth_event writes use a separate NullPool session.
-- Never use the request session for auth_event logging.
-- Always close session in finally block — NullPool does not pool connections.
--
-- ── No schema change ──────────────────────────────────────────────────────────
--
-- This migration is documentation only. The auth_events table schema
-- (action VARCHAR(50), failure_reason VARCHAR(50)) already supports
-- all new values without modification.
SELECT 1;  -- no-op to make migration runners happy
