.PHONY: run test test-integration build up down seed lint format migrate migration typecheck semgrep coverage

run:
	uvicorn api.main:app --reload --host 0.0.0.0 --port 8000

test:
	pytest tests/unit tests/integration -v

# Integration tests against a DISPOSABLE Postgres. Spins an ephemeral
# postgres:16-alpine on port 55432 (clear of the compose stack on 5432),
# points both the app (DATABASE_URL) and the tests (WRAPSEC_TEST_PG_URL)
# at it so auth and data share one throwaway DB, then removes it -- even
# if the tests fail. The dev compose DB is never touched. Requires Docker;
# without it the integration tier skips gracefully under plain `make test`.
test-integration:
	@bash -c 'set -e; \
	CID=$$(docker run --rm -d -e POSTGRES_USER=wrapsec -e POSTGRES_PASSWORD=wrapsec -e POSTGRES_DB=wrapsec_test -p 55432:5432 postgres:16-alpine); \
	trap "docker rm -f $$CID >/dev/null 2>&1 || true" EXIT; \
	echo "waiting for disposable postgres..."; \
	for i in $$(seq 1 30); do docker exec $$CID pg_isready -U wrapsec -d wrapsec_test >/dev/null 2>&1 && break; sleep 1; done; \
	URL=postgresql+asyncpg://wrapsec:wrapsec@localhost:55432/wrapsec_test; \
	DATABASE_URL=$$URL WRAPSEC_TEST_PG_URL=$$URL TESTING=true pytest tests/integration -v'

# Combined unit + integration coverage over the server code (config in .coveragerc).
# Spins a disposable PostgreSQL so the integration tier runs. Writes an HTML report.
coverage:
	@bash -c 'set -e; \
	CID=$$(docker run --rm -d -e POSTGRES_USER=wrapsec -e POSTGRES_PASSWORD=wrapsec -e POSTGRES_DB=wrapsec_test -p 55432:5432 postgres:16-alpine); \
	trap "docker rm -f $$CID >/dev/null 2>&1 || true" EXIT; \
	for i in $$(seq 1 30); do docker exec $$CID pg_isready -U wrapsec -d wrapsec_test >/dev/null 2>&1 && break; sleep 1; done; \
	URL=postgresql+asyncpg://wrapsec:wrapsec@localhost:55432/wrapsec_test; \
	DATABASE_URL=$$URL WRAPSEC_TEST_PG_URL=$$URL TESTING=true coverage run -m pytest tests/unit tests/integration -q; \
	coverage html; \
	coverage report'

# Apply pending Alembic migrations. Also runs automatically on API startup.
migrate:
	alembic upgrade head

# Generate a new autogenerated migration.
# Usage: make migration MSG="add webhook_signing_secret table"
migration:
	alembic revision --autogenerate -m "$(MSG)"

eval:
	python tests/eval/run_evaluation.py
	pytest tests/eval/test_redteam.py -v

build:
	docker compose -f infrastructure/docker/docker-compose.yml build

up:
	@bash scripts/write_metrics_token.sh
	docker compose -f infrastructure/docker/docker-compose.yml up -d

down:
	docker compose -f infrastructure/docker/docker-compose.yml down

up-dev:
	docker compose -f infrastructure/docker/docker-compose.yml up -d postgres redis

logs:
	docker compose -f infrastructure/docker/docker-compose.yml logs -f

seed:
	python scripts/seed_data.py

lint:
	ruff check .

format:
	ruff format .

# Static type checking, scoped to the Python SDK (config in the repo root).
typecheck:
	pyright

# Static application-security scan (Semgrep). NOT a required PR gate -- it runs on
# a schedule / on demand via .github/workflows/security-semgrep.yml. The p/*
# rulesets are fetched live from the Semgrep registry, so the same pinned binary
# returns different findings from one run to the next (non-deterministic); its
# findings are reviewed, not merge-blocking. Path excludes live in .semgrepignore;
# --error fails the run on any finding.
#
# Two rules are excluded deliberately (each verified 100% false-positive here):
#   * detected-stripe-api-key -- WrapSec has no Stripe integration; the rule only
#     ever matches our own wsk_live_* API-key format in test fixtures (pattern
#     collision), so it can never produce a true positive.
#   * logger-credential-disclosure -- fires on auth_event log TEMPLATES that
#     contain credential words while the code logs identifiers (user_id, trace_id,
#     reason), never secret data (verified line-by-line); the log scrubber is the
#     actual control.
# Remaining one-off false positives carry an inline `# nosemgrep: <rule>` reason.
#
# The scheduled workflow and local runs use this SAME target. On Windows run it
# via Docker:
#   docker run --rm -v "$$PWD:/src" -w /src semgrep/semgrep:1.172.0 semgrep scan $(SEMGREP_RULES) $(SEMGREP_SKIP) --error --metrics off .
SEMGREP_RULES := --config p/python --config p/security-audit --config p/secrets
SEMGREP_SKIP  := --exclude-rule generic.secrets.security.detected-stripe-api-key.detected-stripe-api-key --exclude-rule python.lang.security.audit.logging.logger-credential-leak.python-logger-credential-disclosure
semgrep:
	semgrep scan $(SEMGREP_RULES) $(SEMGREP_SKIP) --error --metrics off .

# Reproduce the OS-divergent CI checks (Linux ruff + dashboard build) in Docker
# before pushing, so Windows-invisible failures (e.g. ruff EXE001) surface early.
# The other gates run faster locally: make typecheck / coverage / eval.
ci-local:
	bash scripts/ci-local.sh

clean:
	find . -type d -name __pycache__ -exec rm -rf {} +
	find . -type f -name "*.pyc" -delete