#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 WrapSec. All rights reserved.
# WrapSec v1.0 | AI Security Gateway - https://wrapsec.com

"""
Locale catalog validator + generator (the one pipeline).

Canonical source of truth (framework-independent):
    locales/_meta.json   -- supported_locales / default_locale / catalog_version
    locales/<loc>/*.json -- localized text (ICU), domain-split by namespace

This tool VALIDATES the canonical catalog, then GENERATES every consumer
artifact. No consumer maintains its own copy of the config or the text:
    errors/errors_en.generated.json          -- backend English map
    dashboard/messages/<loc>.json            -- frontend message catalog (one
                                                merged, namespace-keyed file per
                                                locale, for next-intl)
    dashboard/messages/locale-config.json    -- frontend locale config (supported
                                                locales + default + catalog_version)

Run whenever locales/ changes:

    python scripts/gen_locale_catalogs.py

CI enforces freshness (committed artifacts must equal a fresh regenerate) and the
validations below, so a forgotten run -- or a hand-edited consumer copy -- fails.

ICU VALIDATION IS LAYERED (deliberate):
- The UI FRAMEWORK (next-intl) validates EXECUTABLE ICU MessageFormat syntax at
  dashboard BUILD time (`next build`) -- the authoritative compile.
- This framework-INDEPENDENT generator performs a dependency-light STRUCTURAL
  validation (balanced braces / well-formed argument delimiters) BEFORE generating
  consumer artifacts, so a malformed message is caught at generation time without
  pulling an ICU engine into the backend/build tooling.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parent.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from errors.catalog import ERROR_CATALOG, VALIDATION_CATALOG  # noqa: E402
from services.localization import _validate_meta               # noqa: E402

LOCALES_DIR    = REPO_ROOT / "locales"
META_FILE      = LOCALES_DIR / "_meta.json"

BACKEND_MAP    = REPO_ROOT / "errors" / "errors_en.generated.json"
DASH_MESSAGES  = REPO_ROOT / "dashboard" / "messages"
DASH_CONFIG    = DASH_MESSAGES / "locale-config.json"

# Domain namespaces every locale catalog must provide (docs sec 21). Reserved
# enterprise namespaces (policies/mcp/rag/agents) are added when they ship.
REQUIRED_NAMESPACES = ("common", "errors", "forms", "notifications", "pages")

GENERATED_WARNING = (
    "AUTO-GENERATED by scripts/gen_locale_catalogs.py from locales/. Do not edit "
    "by hand; edit the canonical locale source and regenerate."
)


# -- validation -----------------------------------------------------
def _icu_structural_check(key: str, text: str) -> None:
    """Dependency-light structural check: ICU curly-brace delimiters must be
    balanced. Executable ICU syntax is validated by next-intl at build time."""
    depth = 0
    for ch in text:
        if ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth < 0:
                raise SystemExit(f"ICU error in '{key}': unbalanced closing brace")
    if depth != 0:
        raise SystemExit(f"ICU error in '{key}': unbalanced opening brace")


def _flatten(node: Any, prefix: str, out: dict[str, str]) -> None:
    if isinstance(node, dict):
        for key, value in node.items():
            _flatten(value, f"{prefix}.{key}" if prefix else key, out)
    elif isinstance(node, str):
        out[prefix] = node
    else:
        raise SystemExit(f"Non-string leaf at '{prefix}': {type(node).__name__}")


def load_namespaces(locale: str) -> dict[str, Any]:
    """Parsed namespace objects for one locale. Validates that every required
    namespace file exists and that every string leaf is structurally valid ICU."""
    loc_dir = LOCALES_DIR / locale
    if not loc_dir.is_dir():
        raise SystemExit(f"Missing catalog directory for locale '{locale}': {loc_dir}")
    namespaces: dict[str, Any] = {}
    for ns in REQUIRED_NAMESPACES:
        path = loc_dir / f"{ns}.json"
        if not path.exists():
            raise SystemExit(f"Missing namespace '{ns}' for locale '{locale}': {path}")
        with path.open(encoding="utf-8") as fh:
            data = json.load(fh)
        flat: dict[str, str] = {}
        _flatten(data, ns, flat)
        for key, text in flat.items():
            _icu_structural_check(key, text)
        namespaces[ns] = data
    return namespaces


def load_meta() -> dict[str, Any]:
    with META_FILE.open(encoding="utf-8") as fh:
        data = json.load(fh)
    _validate_meta(data)   # single source of the config invariant
    return data


def _flatten_locale(locale: str) -> dict[str, str]:
    flat: dict[str, str] = {}
    for ns, data in load_namespaces(locale).items():
        _flatten(data, ns, flat)
    return flat


# -- consumer artifacts ---------------------------------------------
def build_backend_map() -> dict[str, Any]:
    """The committed backend English map: exactly the localization keys the Error
    Catalog references, resolved from the canonical English text."""
    meta = load_meta()
    flat = _flatten_locale("en")
    required = {m.localization_key for m in ERROR_CATALOG.values()}
    required.update(VALIDATION_CATALOG.values())

    missing = sorted(k for k in required if k not in flat)
    if missing:
        raise SystemExit("Missing English text for catalog keys: " + ", ".join(missing))

    return {
        "__generated__": {
            "warning":         GENERATED_WARNING,
            "source":          "locales/en/*.json",
            "generator":       "scripts/gen_locale_catalogs.py",
            "catalog_version": meta["catalog_version"],
        },
        "messages": {key: flat[key] for key in sorted(required)},
    }


def build_dashboard_messages() -> dict[str, dict[str, Any]]:
    """One merged, namespace-keyed message object per locale, as the dashboard
    consumes it (`{common:..., errors:..., forms:..., notifications:..., pages:...}`).
    Verbatim canonical content (no injected marker) so next-intl reads clean
    namespaces; freshness is enforced by the guard, not a marker."""
    meta = load_meta()
    return {loc: load_namespaces(loc) for loc in meta["supported_locales"]}


def build_locale_config() -> dict[str, Any]:
    """The frontend's locale config -- the ONLY place the dashboard learns which
    locales are supported. Derived from _meta.json; never hand-edited."""
    meta = load_meta()
    return {
        "__generated__": {
            "warning":   GENERATED_WARNING,
            "source":    "locales/_meta.json",
            "generator": "scripts/gen_locale_catalogs.py",
        },
        "catalog_version":   meta["catalog_version"],
        "default_locale":    meta["default_locale"],
        "supported_locales": list(meta["supported_locales"]),
    }


def _serialize(payload: Any) -> str:
    return json.dumps(payload, indent=2, ensure_ascii=False, sort_keys=False) + "\n"


def write_all() -> None:
    BACKEND_MAP.write_text(_serialize(build_backend_map()), encoding="utf-8")
    print(f"Wrote {BACKEND_MAP.relative_to(REPO_ROOT)}")

    DASH_MESSAGES.mkdir(parents=True, exist_ok=True)
    for locale, namespaces in build_dashboard_messages().items():
        path = DASH_MESSAGES / f"{locale}.json"
        path.write_text(_serialize(namespaces), encoding="utf-8")
        print(f"Wrote {path.relative_to(REPO_ROOT)}")

    DASH_CONFIG.write_text(_serialize(build_locale_config()), encoding="utf-8")
    print(f"Wrote {DASH_CONFIG.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    write_all()
