#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 WrapSec. All rights reserved.
# WrapSec v1.0 | AI Security Gateway - https://wrapsec.com

"""
Codegen: build the backend-owned English error map from the localization catalog.

Reads the canonical English text in locales/en/*.json and writes the flattened,
namespaced subset the backend Error Catalog references to
errors/errors_en.generated.json. The backend loads THAT file at startup -- it
never reads the frontend locales at runtime, so the API stands alone (CLI, SDK,
MCP, and Gateway are future consumers of the same generated artifact).

JSON has no comments, so the file self-labels via a reserved "__generated__"
key; the loader skips it. Run this whenever locales/en/errors.json or
locales/en/forms.json changes:

    python scripts/gen_error_catalog.py

CI enforces freshness (the committed file must equal a fresh regenerate), so a
forgotten run -- or a hand-edit -- fails the build.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parent.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from errors.catalog import ERROR_CATALOG, VALIDATION_CATALOG  # noqa: E402

LOCALES_EN_DIR = REPO_ROOT / "locales" / "en"
META_FILE      = REPO_ROOT / "locales" / "_meta.json"
GENERATED_FILE = REPO_ROOT / "errors" / "errors_en.generated.json"

GENERATED_WARNING = (
    "AUTO-GENERATED by scripts/gen_error_catalog.py from locales/en/*.json. "
    "Do not edit by hand; edit the locale source and regenerate."
)


def _flatten(node: Any, prefix: str, out: dict[str, str]) -> None:
    """Flatten a nested locale object into dotted keys (a.b.C -> 'a.b.C')."""
    if isinstance(node, dict):
        for key, value in node.items():
            _flatten(value, f"{prefix}.{key}" if prefix else key, out)
    elif isinstance(node, str):
        out[prefix] = node
    else:
        raise ValueError(f"Non-string leaf at '{prefix}': {type(node).__name__}")


def flatten_locale_en() -> dict[str, str]:
    """All English strings, keyed by '<filename>.<dotted-path>'."""
    flat: dict[str, str] = {}
    for path in sorted(LOCALES_EN_DIR.glob("*.json")):
        with path.open(encoding="utf-8") as fh:
            data = json.load(fh)
        _flatten(data, path.stem, flat)
    return flat


def required_keys() -> set[str]:
    """Every localization key the backend Error Catalog can resolve."""
    keys = {meta.localization_key for meta in ERROR_CATALOG.values()}
    keys.update(VALIDATION_CATALOG.values())
    return keys


def build_generated() -> dict[str, Any]:
    """The exact dict that should be committed to errors_en.generated.json."""
    flat = flatten_locale_en()
    with META_FILE.open(encoding="utf-8") as fh:
        catalog_version = json.load(fh).get("catalog_version", 0)

    missing = sorted(k for k in required_keys() if k not in flat)
    if missing:
        raise SystemExit(
            "Missing English text for catalog keys (add them to locales/en/): "
            + ", ".join(missing)
        )

    messages = {key: flat[key] for key in sorted(required_keys())}
    return {
        "__generated__": {
            "warning":         GENERATED_WARNING,
            "source":          "locales/en/*.json",
            "generator":       "scripts/gen_error_catalog.py",
            "catalog_version": catalog_version,
        },
        "messages": messages,
    }


def _serialize(payload: dict[str, Any]) -> str:
    return json.dumps(payload, indent=2, ensure_ascii=False, sort_keys=False) + "\n"


def write_generated() -> None:
    GENERATED_FILE.write_text(_serialize(build_generated()), encoding="utf-8")
    print(f"Wrote {GENERATED_FILE.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    write_generated()
