name: Publish Node SDK

on:
  push:
    tags:
      - "sdk-node-v*"

jobs:
  publish:
    runs-on: ubuntu-22.04

    defaults:
      run:
        working-directory: sdk/node

    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"

      - name: Install and build
        run: |
          npm ci
          npm run build

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
